### ISSUE TITLE
Provide control over how modeling of forest carbon storage in wood and paper products is implemented

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/WARMer#2]
## Background
WARM v15 olca represents carbon storage in wood products like dimensional lumber as a output 
`Carbon/Resource/biotic` elementary flow with a negative value, as shown here

![image](https://user-images.githubusercontent.com/5831306/186553802-cedcb9bf-539b-4113-92b5-2ab2081e1fcb.png)

The method behind this is documented in WARMv15 [Background chapters](https://www.epa.gov/sites/default/files/2020-12/documents/warm_background_v15_10-29-2020.pdf), specifically section 4.4.3,  "Changes in in-use product carbon pool"

## Issue
The assumption of forest carbon storage in WARM is that with recycling or source reduction of paper and wood products displacing the need, and thus harvest, of forest, and thus more carbon is stored in the forest. This is an induced and indirect effect that could be handled in various ways in LCA, possibly considered or not. Generally in an attributional LCA, it would not be considered -- these kinds of induced effects are reserved for consequential LCA. For WARMer, which is agnostic to modeling assumptions, the current setup does not allow the user with a choice of these assumptions.  Therefore WARMer needs to provided options for handling forest carbon storage

**Comment by bl-young** [comment]
I think this one is more straightforward in that if desired the  `carbon/resource/biotic` can be removed as that flow only applies in these cases.
![image](https://user-images.githubusercontent.com/44471635/187765463-dd509f63-5b22-4c94-ac37-e174c592f955.png)

**Comment by bl-young** [comment]
Regarding the implementation of the control, seems like we need to allow for any number of these controls to be applied to a dataset, so perhaps an optional list parameter for [`get_exchanges()`](https://github.com/USEPA/WARMer/blob/main/warmer/olca_warm_matrix_io.py#L390-L391). Each specific control might require a quasi-unique function. Kind of like how things are handled for [filters in stewi](https://github.com/USEPA/standardizedinventories/blob/master/stewi/filter.yaml)

**Comment by bl-young** [comment]
very early implementation started on the controls branch here https://github.com/USEPA/WARMer/commit/b0dd68c4f1f6956804431a4d93ccf3dc0e6a14b7
